# Generated by Django 5.1.7 on 2024-05-22 12:00

from django.db import migrations


def create_initial_products(apps, schema_editor):
    """Creates six sample products with details and image paths."""
    Product = apps.get_model('ecommerce', 'Product')
    Product.objects.bulk_create([
        Product(
            name="Wireless Headphones",
            description="High-fidelity wireless headphones with noise-cancellation and a 20-hour battery life.",
            price=199.99,
            image="https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=1080&auto=format&fit=crop"
        ),
        Product(
            name="Smartwatch Pro",
            description="A sleek smartwatch with fitness tracking, notifications, and a vibrant AMOLED display.",
            price=249.50,
            image="https://images.unsplash.com/photo-1546868871-7041f2a55e12?q=80&w=1080&auto=format&fit=crop"
        ),
        Product(
            name="4K Action Camera",
            description="A rugged, waterproof action camera that captures stunning 4K video.",
            price=179.99,
            image="https://images.unsplash.com/photo-1566513420987-b631702bbe33?q=80&w=1080&auto=format&fit=crop"
        ),
        Product(
            name="Portable SSD",
            description="A 1TB portable solid-state drive with ultra-fast transfer speeds.",
            price=89.00,
            image="https://images.unsplash.com/photo-1619891940229-f35d94513a15?q=80&w=1080&auto=format&fit=crop"
        ),
        Product(
            name="Mechanical Keyboard",
            description="A backlit mechanical keyboard with responsive switches for gaming and typing.",
            price=125.00,
            image="https://images.unsplash.com/photo-1618384887924-2620e42bb882?q=80&w=1080&auto=format&fit=crop"
        ),
        Product(
            name="Bluetooth Speaker",
            description="A compact and powerful Bluetooth speaker with rich bass and 360-degree sound.",
            price=75.50,
            image="https://images.unsplash.com/photo-1589256469028-5497b38c9a7a?q=80&w=1080&auto=format&fit=crop"
        ),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),  # This should be the migration that created the Product model
    ]

    operations = [
        migrations.RunPython(create_initial_products),
    ]